### ISSUE TITLE
Server Crashes When Close to Primordial Caves

### ISSUE THREAD

**Issue by autumnly24** [AlexModGuy/AlexsCaves#715] opened 2023-12-17 20:05 UTC
I'm aware of what the issue is, it's an incompatibility with Twigs, however, you've marked that issue as closed when it's still happening, and I want to make sure you're still aware of the issue so you can fix it. 

I have a server running both Twigs and Alex's Caves and it's not possible to remove either mods at this point, so the bug is making it very difficult for players to explore, because they keep coming across these biomes and bricking the server, which means I have to load backups.

As far as I've seen, it works fine with both Forlorn and Toxic caves (as some of our players have explored those) but we've had numerous confirmed crashes with the Primordial Caves.

I don't want to sound rude, it's just that it's a bit frustrating having a large portion of the world that just crashes the game when you go near it. Best of luck resolving the issue!

**Comment by AlexModGuy** [comment] 2023-12-17 20:59
you have to remove one of the mods since theyre incompatible.

**Comment by AlexModGuy** [comment] 2023-12-17 21:03
dupe of  #84

**Closed by AlexModGuy** 2023-12-17 21:03 UTC
Labels: Incompatiblity

**Comment by autumnly24** [comment] 2023-12-17 23:37
Are you able to work on a fix? Like, is it something you could fix, or is it an issue that only the Twigs devs could fix? It would corrupt the server world to remove either mod, so I can't just do that, but if you have any info I'd like to know.
