### ISSUE TITLE
if i look on ray cat, or on irritated mobs or players i have lags and fps drop

### ISSUE THREAD

**Issue by artemius00789** [AlexModGuy/AlexsCaves#616] opened 2023-11-13 16:38 UTC
hey everyone if i look on ray cat, or on irritated mobs or players, i have fps drop
version of the alex caves 1.0.8
version of the citadel 2.4.9

**Comment by PeglinX** [comment] 2023-11-13 23:55
sounds like a dupe of #157

**Comment by AlexModGuy** [comment] 2023-11-18 17:20
dupe https://github.com/AlexModGuy/AlexsCaves/issues/157

**Closed by AlexModGuy** 2023-11-18 17:20 UTC

**Comment by artemius00789** [comment] 2023-12-02 15:56
Alex
i have lags if i on wide screen
