### ISSUE TITLE
World appears to stop loading when near the new biomes

### ISSUE THREAD

**Issue by Lambda-System** [AlexModGuy/AlexsCaves#159] opened 2023-10-20 14:48 UTC
the title just says it. whenever i get near one of the new biomes (or if we have to be specific, the Magnetic Caves), its like as if reality itself decided to say "aight, im done"

i can still move around, but new chunks has stopped generating, i cant access my inventory, i cant teleport with the Waystone mod, nothing.

and every time i try to save the game and quit back to title screen, the game stops at loading screen, forcing me to ALT+F4

part of me believe this could be due to mods conflicting, but i am very unsure. i hope im not the only one experiencing this same sort of issue (or similar)

**Comment by AlexModGuy** [comment] 2023-10-20 14:51
it's a mod conflict. Sounds similar to #84

**Comment by BadgerKing21** [comment] 2023-10-20 15:39
> it's a mod conflict. Sounds similar to #84

Do you know specifically what's causing the conflict, or are you still working figuring that out?

**Comment by AlexModGuy** [comment] 2023-10-20 15:52
theres a few mods that are doing this but the most common one seems to be the mod Twigs.

**Comment by BadgerKing21** [comment] 2023-10-20 16:10
> theres a few mods that are doing this but the most common one seems to be the mod Twigs.

Good to know. Thanks mate, you're doing god's work.

**Comment by Lambda-System** [comment] 2023-10-20 18:57
apologies for being hours late, life needed my attention

anyways, i have checked and, although we do have 60 other mods (not counting Citadel and Alex's Caves- duh), none of them are Twigs. I could still send a picture of the mods we are using if that helps anything

**Comment by PeglinX** [comment] 2023-10-30 01:53
Hey the same error. Redstone, mob AI, Rendering, collisions in unloaded chunks, chunk loading, and block updates all stop whenever I load any cave biome. This however doesn’t drop fps. It doesn’t seem to be because of rendering optimisation mods such as Embedium.

**Comment by PeglinX** [comment] 2023-10-30 02:01
Many of the chunks that had previously been loaded become ghost chunks.

**Comment by PeglinX** [comment] 2023-10-30 02:24
News: Twigs was causing my issue, not sure about yours. Maybe try to make another instance adding Worldgen mods in maybe batches of 5 until you find which one causes issues

**Comment by Lambda-System** [comment] 2023-10-30 14:01
i could. but i have noticed that Ferrouslimes are the culprits of why the game is "softlocking". now i am unsure whether this is a mod library issue, or Optifine, being- well, Optifine. ill look into it

**Comment by AlexModGuy** [comment] 2023-12-10 20:40
dupe of #328

**Closed by AlexModGuy** 2023-12-10 20:40 UTC

**Comment by JustAnotherBugReporter** [comment] 2023-12-18 15:36
Forge version?
Use recommended version, 47.2.0
