### ISSUE TITLE
Rendering Error/Golden Frog guide

### ISSUE THREAD

**Issue by MinecraftModderDailyDoseOfMods** [AlexModGuy/AlexsCaves#818] opened 2024-02-21 10:34 UTC
I'm trying to summon the golden frog and doesn't work, when im using /locate biome alexscave:primodial_caves, it completely stop rendering after it loading. If it's not a bug, show me a command to spawn the golden frog.

**Comment by MinecraftModderDailyDoseOfMods** [comment] 2024-02-21 10:37
Like /summon for golden frog. I try using {Varient} nbt but doesn't work either. In the future, may be making using amber curiosity on frog to make it gold.

**Comment by MinecraftModderDailyDoseOfMods** [comment] 2024-02-21 10:40
Extra, crash on 1.1.0, both citadel and the mod is in newest version:
[17:38:27] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.forEach(HashMap.java:1424)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.texture.TextureManager.close(TextureManager.java:178)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.close(Minecraft.java:1070)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91393_(Minecraft.java:1043)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:234)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by JustAnotherBugReporter** [comment] 2024-02-21 12:57
/summon minecraft:frog ~ ~ ~ {variant:"alexscaves:primordial"}

**Comment by AlexModGuy** [comment] 2024-02-24 02:41
> Extra, crash on 1.1.0, both citadel and the mod is in newest version: [17:38:27] [Render thread/ERROR]: Shutdown failure! java.util.ConcurrentModificationException at java.base/java.util.HashMap.forEach(HashMap.java:1424) at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.texture.TextureManager.close(TextureManager.java:178) at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.close(Minecraft.java:1070) at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91393_(Minecraft.java:1043) at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:234) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

post the full log this tells me next to nothing

**Comment by MinecraftModderDailyDoseOfMods** [comment] 2024-02-24 03:02
I will send it tomorrrow, issue still persists


Vào Th 7, 24 thg 2, 2024 vào lúc 09:41 Alexthe668 <
***@***.***> đã viết:

**Comment by AlexModGuy** [comment] 2024-03-01 18:12
either dupe of #84 or #49

**Closed by AlexModGuy** 2024-03-01 18:12 UTC
