### ISSUE TITLE
Cave's images not shown properly in the Cave Compendium with Embedium installed

### ISSUE THREAD

**Issue by TysonNguyen619** [AlexModGuy/AlexsCaves#808] opened 2024-02-20 06:21 UTC
Just a graphical bug no biggie. So, the first page for every cave's chapter contain the image associated with each caves. Currently, it doesn't cover the entire page but is rather pulled to one side.

Some more info: 
- Alex's caves - 1.1.0
- Citadel - 2.5.3
- Forge 1.20.1 - 47.2.20
https://github.com/AlexModGuy/AlexsCaves/assets/150374817/62b67f9f-2411-4bbe-8aa6-23fc4bae811b

**Comment by Vinzound** [comment] 2024-02-20 22:21
I have exactly the same problem :(

**Comment by JustAnotherBugReporter** [comment] 2024-02-21 22:39
Downgrade to recommended, for the mod is based on 47.2.0

**Comment by GauntAndreX8** [comment] 2024-02-22 03:09
lol i have that too

**Comment by ZerbieSlug** [comment] 2024-02-23 23:29
This glitch seems to come from an outdated Forge version.

When you update Forge to the latest version, the books should display like normally.

**Comment by Vinzound** [comment] 2024-02-24 06:26
It is not true, I already tried to see if the glitch was solved in forge 4.2.20 (the newest version at the time of writing this), and the problem is still present.

**Comment by Vinzound** [comment] 2024-02-24 06:44
I am realizing that this glitch is only happening to me if I have the Embeddium mod activated

**Comment by TysonNguyen619** [comment] 2024-02-24 10:37
That seems like to problem because I have Embeddium insttalled too

**Comment by embeddedt** [comment] 2024-02-25 00:35
This is an Embeddium bug and will be fixed in the next release.

However, @AlexModGuy I think you didn't intend to call `VertexConsumer#uv` twice per vertex [here](https://github.com/AlexModGuy/AlexsCaves/blob/f50b43f134f5cf24756c7378fc6bf27a7d6edbc5/src/main/java/com/github/alexmodguy/alexscaves/client/gui/book/widget/ImageWidget.java#L75-L77); vanilla just ignores the second call but it seems messy regardless.

**Closed** 2024-02-29 17:39 UTC
Labels: Incompatiblity
