### ISSUE TITLE
Raycat Lag the game every time i look at him

### ISSUE THREAD

**Issue by SilvsLovesCapybaras** [AlexModGuy/AlexsCaves#619] opened 2023-11-14 17:52 UTC
every time i look at a raycat my minecraft gets a fps drop, mabey its bescause the lighting effect

**Comment by PeglinX** [comment] 2023-11-14 21:29
dupe of https://github.com/AlexModGuy/AlexsCaves/issues/157 It,s already worked on

**Comment by AlexModGuy** [comment] 2023-11-18 17:19
check ou tthe radiation option in the client config

**Closed by AlexModGuy** 2023-11-18 17:19 UTC
